# Generated by Django 5.1.6 on 2025-03-04 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(default='', max_length=300)),
                ('event_name_id', models.CharField(blank=True, editable=False, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('invitations', models.IntegerField(default=0)),
                ('cellphone', models.CharField(max_length=100)),
                ('attend', models.BooleanField(default=False)),
                ('extraGuests', models.CharField(default='', max_length=300)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='sisu.event')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('evento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='sisu.event')),
            ],
        ),
    ]
