# Generated by Django 5.1.6 on 2025-03-04 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisu', '0002_remove_host_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='sisu.event'),
        ),
    ]
