# Generated by Django 5.1.6 on 2025-03-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisu', '0003_host_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_link_invitation',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='invitation_link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
