# Generated by Django 5.1.6 on 2025-03-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisu', '0004_event_host_link_invitation_event_invitation_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='attend',
            new_name='assists',
        ),
    ]
