# Generated by Django 5.1.6 on 2025-03-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisu', '0005_rename_attend_guest_assists'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='table_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='host_link_invitation',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='invitation_link',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='guest',
            name='extraGuests',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
